### ISSUE TITLE
Media management

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#48]
Cities use/include images and PDFs in pages. Therefore back end users need a convenient way to manage these files. Most commons file types:
* PDF
* PNG
* JPEG

Other common image formats need to be supported as well.

The following additional features should be supported:
* Data should be stored in a directory defined in the settings.py
* enable replacement of files (update files without changing download URL)
* add alt text to enhance accessibility (probably as required field)
* security checks of uploaded files
* Nice to have feature: data deduplication. Users are uploading lots of duplicated content. We could save a lot of disk space with deduplication of stored files.
* Uploaded files should not immediately be publicly available.
* Scaling of images for the apps
* Optimazation, for PNG lossless, for example with optipng, for JPEG with defined compression levels, i.e. 85. See #118 
* Please have a look at caching/storing rules of the app. Ask app team about current implementation.

**Comment by benginoe** [comment]
Should have possibilite to provide alt-text for alt-tag in html.

**Comment by timoludwig** [comment]
- enable replacement of files (without having to change the name/id/url in the content)
- add alt text to enhance accessibility (probably as required field)
- security checks of uploaded files

**Comment by svenseeberg** [comment]
Nice to have feature: data deduplication. Users are uploading lots of duplicated content. We could save a lot of disk space with deduplication of stored files.

**Comment by benginoe** [comment]
Image (JPEG/PNG) optimization via e.g. tinyjpg.com #118

**Comment by svenseeberg** [comment]
There is also a CLI tool named optipng

**Comment by RoyJia** [comment]
### Option 1. Try to use django-filer module, django Filer is a file management application for django that makes handling of files and images a breeze

#### CURRENTLY:

 - So far, we are able to use django-filer with admin account and with its own UI(different with integreat) - http://localhost:8888/admin/filer/
 - But it could be config to other user by the Django authorzation system.

#### TO DO:

 - 1. Move django-filer to user interface form Django admin. Roy: I tried but I dont find a way to integrate it, may people know, who is more expertise for Django. 
 - 2. Fit django-filer UI to same with cms-django
 

 
### Option 2. Create new file management module for cms-django - Media Library

#### CURRENTLY:

 - I created Media Library page
 - Able to upload/view/download/delete file, files is stored in `MEDIA_URL = '/media/'` and file info is stored with Document Model
 - Util method `save_file` is created for all files saving, because the file info would be saved to database

#### REVIEW:

 - "enable replacement of files (update files without changing download URL)" - could implement this with edit funtion  - A
 - "add alt text to enhance accessibility (probably as required field)" - since I did not differentiate file type, so I setup rel instead alt in some table cell
 - "security checks fo uploaded files" - C
 - "Nice to have feature: data deduplication.." - D
 - "Uploaded files should not immediately be publicly available" - How it should be? - E
 - "Scaling of images for the apps" - could be after support thumbnail - B
 - "Optimazation, for PNG lossless, for example with optipng, for JPEG with defined compression levels, i.e. 85." - F

#### TO DO:

 - A. Implement eidt
	 - issue: when update, new medel instance will be added
 - B. To support thumbnail
 - C. To support security checks fo uploaded files
 - D. Deduplication
 - E
 - F. Optimazation
 - G. To support pagination
 - H. To supoort search(within Media Library)
 - I. To support order by name/create_date...

**Comment by timoludwig** [comment]
Just for the record: This is already partially solved in the branch [media_management](https://github.com/Integreat/cms-django/tree/feature/media_management).
