### ISSUE TITLE
Object-based search on list overviews

### ISSUE THREAD

**Issue by sascha11110** [Integreat/integreat-cms#63]
To speed up navigation, an entity based search would also help, limiting it to only the entity displayed in the current list.

**Comment by svenseeberg** [comment]
Entity again is page/event/location?

**Comment by sascha11110** [comment]
Yep

**Comment by ulliholtgrave** [comment]
@svenseeberg I suggest to move the issue to the Version 1.0 milestone as search fields are important feature that we have in wordpress as well. Your opinion?

**Comment by timoludwig** [comment]
This is needed for the following model lists:

- Region list
- Admin Media Library
- Admin User list
- Admin/Technical Feedback
- Region Media Library
- Page Tree
- Event list
- POI List
- Push News
- Region Feedback
- Region User list

The implementation for all lists should be nearly identical, so please try to use shared utility functions as much as possible.
Only the search for the media library is different, since it is implemented in preact native.

If feasible, try to do dynamic AJAX calls which then render a sub-template of the table contents instead of reloading the whole page.
Also think about including additional fields where suitable, e.g. also searching the content of pages if there is no exact match in the titles... (or directly search all fields but show matches in the name/title fields at the top) - but that's optional and can be skipped if it's too complicated.


Lists which can probably be omitted:
- Languages
- Roles
- Organizations
- Offer Templates
- Language Tree

**Comment by ulliholtgrave** [comment]
First solution for version 1.0 can be the search by extending the views. Then the page is reloaded each time, but it is by far the simplest variant. However, it needs another button for the search field.

**Comment by svenseeberg** [comment]
The page tree view should implement the search in JavaScript, as all pages are already present in the browser and searching in the back end will take a relatively long time.
