### ISSUE TITLE
Improve content language switcher

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#630]
### Motivation

At the moment, switching the content language is very unintuitive, you have to click on the small flags in the table:

![Screenshot_2021-01-13 Integreat CMS](https://user-images.githubusercontent.com/16021269/104476574-af6a6780-55c0-11eb-9bea-eb27ee1cc6b2.png)

### Proposed Solution

Implement something similar to the current design in wordpress:

![Screenshot_2021-01-13 Seiten ‹ Testumgebung — WordPress](https://user-images.githubusercontent.com/16021269/104476751-df196f80-55c0-11eb-8109-349378d3f362.png)

Highlight the currently selected language.

This has to be done for all content models:
- [ ] Pages
- [ ] Events
- [ ] POIs
- [ ] Push Notifications

**Comment by dkehne** [comment]
wait. i like the idea of make it leaner and only have the symbols to navigate to the translations. especially because most municipalities don't use the embed-translation-service because they use xliff and solve the translation issue by external partners (or hopefully in future more by automated translations.

So i my opinion we should start with the small-flag variant only. if this is a show stopper somewhere we can build the "wordpress-like" second way...

**Comment by timoludwig** [comment]
@dkehne This idea came up during today's coworking when we talked about the page filter (issue #240)...
The thing is that it is hard to filter e.g. for all arabic translations which are outdated when the language switcher is not easy to use.
So even for cities which just want to export xliffs, it's probably good to have this filter options available, or am I missing something?
Alternatively, we can embed the language switching into the filtering UI, e.g. with a select field. But only relying on the flags is a bit confusing I think.

**Comment by dkehne** [comment]
Currently this is done by an additional menu point: WPML -> Übersetzungsmanagement, which is only used by 10-20% of the municipalities on its own and in 80-90% of the cases by the municipality team because every mistake made there costs money (in case of wrong translations).

I would suggest an additional menu point as in the current system which is in 80% of the instances only visible to our team and where we have the possibility to filter which pages we want to export based on the filters mentioned from sven in #240 . We can add another dropdown to choose the target language. 

Menupoint: Translation Export / Übersetzungsexport
We could also implement the import-function there (upload xliff-file)

From the normal pages view it's only possible to download single xliffs by clicking the icon and to navigate to the split-screen-view for internal translators.

**Comment by dkehne** [comment]
I don't want to overload the pages-page...

**Comment by svenseeberg** [comment]
I would like to see a "best of both worlds" approach: the simplicity of the language flags combined with the leaner view we already have. To be more precise: I would avoid a long (text) list of all available languages. We could add a button "Switch language" which opens a language selection dialog, shown as a nice list (overlay?), including eye candy (flags).

**Comment by timoludwig** [comment]
@dkehne I noticed that the language switcher is also necessary for the PDF export, so it has to be available to all users, not only expert users.

@svenseeberg Sounds good. I'd like to indicate the current language somewhere in the switcher on first glance, so maybe something similar to this?

![language-selection2](https://user-images.githubusercontent.com/16021269/106366059-b96ac500-6339-11eb-96ad-4d14e3eac228.jpg)

**Comment by dkehne** [comment]
I am not sure if we really the language switcher in the same way as at the moment (in den top bar). We need it for pdf-export - yes - but we could also realize it with a dropdown there. 

of course i am thinking of it possible too wordpress-like...

**Comment by timoludwig** [comment]
I'm not sure what you mean by "top bar". In Django?
![Screenshot_2021-01-31 Integreat CMS](https://user-images.githubusercontent.com/16021269/106385309-fb464a80-63cf-11eb-8ead-6a5f1a797d2b.png)
This language switcher is for changing the user interface language (currently only German and English are supported) and has nothing to do with the content languages. In fact, we already planned to move the user interface language switcher to the user settings like it is in WordPress (see issue #651) to avoid misunderstandings with the different types of language switching.

If you mean the top-bar in Wordpress (where you can really change the content language):
![Screenshot_2021-01-31 PDF Export ‹ Bad Tölz — WordPress](https://user-images.githubusercontent.com/16021269/106385684-d05cf600-63d1-11eb-8d99-619a9cc20cd6.png)
We think that this is a bad UI decision of WPML - because it places a UI element which only affects some pages in a global place where it's visible on every page. Thus, we're looking for a solution for the language switcher where it's not in the top bar, but somewhere below...

**Comment by dkehne** [comment]
yeah i meant this by top bar. users know that hey can change content language there so we should not use the same ui-element in django for changing the gui-language. but this is sth. you can decide.

for us as munipality-team we can only emphasize that there should no need for any extra trainings when we migrate. of course the django will look a bit different but for non-expert users (~50% users) there shouldn't be any changes which are not intuitive for non-digital-experts.

**Comment by timoludwig** [comment]
> yeah i meant this by top bar. users know that hey can change content language there so we should not use the same ui-element in django for changing the gui-language.

Yes, this is exactly what issue #651 is about.

> for us as munipality-team we can only emphasize that there should no need for any extra trainings when we migrate. of course the django will look a bit different but for non-expert users (~50% users) there shouldn't be any changes which are not intuitive for non-digital-experts.

Yeah, I think we're on the same page here. If it's not possible to design a language switcher which is usable without extra training, we have to use the same solution as in WordPress. However, I'd like to give it a try and only use the WordPress UI as a last resort.
