### ISSUE TITLE
Autosave changes previous version to draft

### ISSUE THREAD

**Issue by Thomas125** [Integreat/integreat-cms#714]
### Describe the Bug
On autosave the prior revision is changed to draft-status.

### Steps to Reproduce

1. Go to pages
2. Open page-editor for an existing page which last revision is PUBLIC.
3. Make some change (e.g. in the text)
4. Wait two minutes (until the autosave is triggered)

### Expected Behavior
A new revision is created with status DRAFT. The revision that already existed, remains unchanged with status PUBLIC.

### Actual Behavior
A new revision is created with status DRAFT. The revision that already existed, remains unchanged, but gets status DRAFT.

### Additional Information
Probably, it also makes sense to add a new status for autosave translations.

This issue depends on:
- Issue #869
- Issue #870

**Comment by timoludwig** [comment]
This is also related to bug #672 maybe this can be fixed at the same time?

**Comment by MizukiTemma** [comment]
I have tried to reproduce the bug but it didn't go as described.

In the editor of the published page with title "initial" und text "initial", an additional word "asdf" was added in the text.
Leaving the editor after an auto save was triggered without any explicit saving, no new revision (version) appeared and the status stayed published (veröffentlicht).

Has the behaviour somehow changed inbetween?

**Comment by timoludwig** [comment]
To reproduce and finally fix this issue, we have to fix #869 and #870 first.

About the issue itself: I think the problem is that a new version is only created if one of the fields "slug", "title" or "text" change:

https://github.com/Integreat/integreat-cms/blob/5d3a30ad71108662c3f45ce8674a71096bdf59f7/src/cms/forms/pages/page_translation_form.py#L103-L107

So if the autosave gets triggered while these values are unchanged, the existing version gets saved with the new draft status.
Normally, this doesn't happen so much, because tinymce is smart enough to trigger the autosave only when something changed, but if we e.g. insert a letter and remove it directly afterwards, tinymce will trigger an autosave but Django will still recognize that the values are unchanged and just sets the status to draft, which is probably not what the user expects.
To circumvent this, we could either create a new version each time the form is submitted, no matter which fields changed, or somehow make sure that the form isn't saved at all when nothing changed and the save is an autosave... For this, we might have to either send an additional parameter to the form submission, or create a new status "autosave" which impacts the form submission in a way that an unchanged form is no longer saved.

**Comment by MizukiTemma** [comment]
@timoludwig 

I have tested again the behaviour after #869 and #870 are fiexed. Now an autosave saves a new version with status Draft (Entwurf (Diese Version wird nicht in den Apps angezeigt.))  and the previous published version remains published (Veröffentlicht (Diese Version wird in den Apps angezeigt.)).

Is this the expected behaviour, isnt it?

Or should the status shown in the page list be public?

**Comment by timoludwig** [comment]
> Is this the expected behaviour, isnt it?

Yes, this is correct. I could only reproduce the described bug in some edge cases, where the slug, title and text fields are unchanged while the auto-save is triggered. So if you e.g. add a letter and remove it afterwards, and then wait until an auto-save happens, the existing version which should be public is converted to a draft again without creating a new version.
And if you then change something and wait again, the "expected" auto-save happens and a new version is created.
Now, this is the exact same result as described in the issue (the previous version converted to draft and a new version created as draft).
Sorry, the issue description is a bit misleading here, the bug is not really triggered when the new version is created, but instead before, when the unchanged page is auto saved. At least that's what I think is going on, because I also couldn't reproduce the exact same behavior as described.
