### ISSUE TITLE
Non-existing page translation PDF export bug

### ISSUE THREAD

**Issue by melegiul** [Integreat/integreat-cms#753]
### Describe the Bug

When user selects a non existing page translation for PDF export, there comes up an uncaught KeyError exception.

### Steps to Reproduce

1. Go to page tree
2. Click on language flag with non-existing translation, e.g. arabic
3. Set checkbox for this translation
4. Select PDF export

### Expected Behavior

Nothing should happen due to missing translation
Alternative: pop up dialog to inform user about non existing page translation

### Actual Behavior

KeyError exception occurs

**Comment by timoludwig** [comment]
Since this only happens when only non-existing translation are selected (as long as there is one existing translation, the non-existing ones just get filtered out and the PDF is generated successfully), I propose to show an error message in this case.

Even though it's not ideal from a UX perspective to open the new tab just for showing an error message, I think in this case it's acceptable because I see no simple way around it and I don't think we should build a complex solution for this rare edge case... just add the error message in the PDF export action and redirect to the page tree in the new tab.

**Comment by melegiul** [comment]
I had just a deeper look at the code and concerning UX perspective I could offer also a third alternative:
This function [toggleBulkActionButton](https://github.com/Integreat/integreat-cms/blob/12b0c12ed86a7aad8f059c12fea51f712ca90c34/src/frontend/js/bulk-actions.ts#L66) is used to toggle the buttons disabled property, so I could add a function that compares some DOM elements (like [no-trans-class](https://github.com/Integreat/integreat-cms/blob/12b0c12ed86a7aad8f059c12fea51f712ca90c34/src/cms/templates/pages/page_tree_node.html#L83)) and disable the button if need.
I think the complexity would be not very high, what you think about this idea?
