### ISSUE TITLE
`TypeError` in event form

### ISSUE THREAD

**Issue by melegiul** [Integreat/integreat-cms#887]
### Describe the Bug

TypeError is thrown for newly created events

### Steps to Reproduce

1. Go to form for creating a new event
2. Enter valid form data
3. Click save
4. See the type error

### Expected Behavior

New event is created by form submission

### Actual Behavior

Exception occurs

### Additional Information

```
TypeError at /augsburg/events/de/new
has_changed() missing 2 required positional arguments: 'initial' and 'data'
```
![Screenshot from 2021-07-07 13-46-24](https://user-images.githubusercontent.com/47010475/124753881-cfecfc00-df29-11eb-9343-7da29fca5054.png)

**Comment by david-venhoff** [comment]
The error originates from this line: https://github.com/Integreat/integreat-cms/blob/3c93fcba93637d700c66a740de788c4a81625705/src/cms/views/events/event_view.py#L187
Apparently, the method `has_changed` takes two arguments which are not specified there. A possible fix would be to replace this line with
```python
            elif "is_recurring" in event_form.changed_data:
```

Unfortunately, this causes another error, when the user removes an existing recurrence rule:
![grafik](https://user-images.githubusercontent.com/78504586/125940529-d5979be8-4d1a-40d6-a1eb-5d84a91b5d8a.png)

This error originates from there:
https://github.com/Integreat/integreat-cms/blob/3c93fcba93637d700c66a740de788c4a81625705/src/cms/views/events/event_view.py#L190

To me it seems like the line above causes this error, because the deletion does not set the recurrence rule to null, just its foreign key. Adding a line below 189:
```python
                event_form.instance.recurrence_rule = None
```
fixes that. However I am not sure why exactly django is throwing the new error, so this is most likely not the best fix.

**Comment by florianhofhammer** [comment]
A possible issue is that `has_changed` determines whether a field value has changed or not based on the field's initial value and the newly assigned (through the `POST`) value (see the [Django docs](https://docs.djangoproject.com/en/3.2/ref/forms/api/#django.forms.Form.has_changed)).
When doing some introspection on `event_form.fields["is_recurring"]`, we see that it's `initial` value is set to `None`. I assume that this is the reason for the error because the comparison then obviously fails.
I'm digging into it!

**Comment by florianhofhammer** [comment]
Interestingly, the [Django documentation](https://docs.djangoproject.com/en/3.2/ref/forms/fields/#django.forms.Field.has_changed) is not really complete here. In fact, the error message basically already gives the solution away and looking at Django's source supports this:

https://github.com/django/django/blob/00ea883ef56fb5e092cbe4a6f7ff2e7470886ac4/django/forms/fields.py#L732-L737

Takeaway: you can call `has_changed` on a form without any arguments but if you want to call it on a field, you have to explicitly provide the two values you want to check.
